17-asp-net-basics/AspNetBasics/AspNetBasics/Models/AddViewModel.cs
using Entities;
using System;
using System.Collections.Generic;

namespace AspNetBasics.Models
{
    public class AddViewModel
    {
        public bool[] prizesIsChecked { get; set; }
        public List<Prize> prizes { get; set; }
        public User User { get; set; }
    }
}

17-asp-net-basics/AspNetBasics/AspNetBasics/Models/ErrorViewModel.cs
using Entities;
using System;
using System.Collections.Generic;

namespace AspNetBasics.Models
{
    public class ErrorViewModel
    {
        public List<Prize> prizes;
        public User User;
    }
}

17-asp-net-basics/AspNetBasics/AspNetBasics/Controllers/HomeController.cs
using AspNetBasics.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetBasics.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

    }
}

17-asp-net-basics/AspNetBasics/AspNetBasics/Controllers/PrizeController.cs
using AspNetBasics.Models;
using BLL;
using DALDB;
using Entities;
using Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetBasics.Controllers
{
    public class PrizeController : Controller
    {

        private readonly PrizeDAL _prizeDAL;
        private readonly PrizeBL _prizeBL;
        public PrizeController()
        {
            var connectionStringBuilder = new SqlConnectionStringBuilder();
            connectionStringBuilder.DataSource = "DESKTOP-34RCMFS\\SQLEXPRESS";
            connectionStringBuilder.InitialCatalog = "usersAndPrizes";
            connectionStringBuilder.IntegratedSecurity = true;

            var connection = connectionStringBuilder.ToString();

            _prizeDAL = new PrizeDAL(connection);
            _prizeBL = new PrizeBL(_prizeDAL);
        }

        public IActionResult Index()
        {
            var prizes = _prizeBL.GetAll();
            return View(prizes);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(int id, string title, string description)
        {
            Prize prize = new Prize(id, title, description);
            _prizeDAL.Add(prize);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _prizeDAL.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var prize = _prizeDAL.Get(id);

            return View(prize);
        }

        [HttpPost]
        public IActionResult Edit(int id, string title, string description)
        {
            Prize prize = new Prize(id, title, description);
            _prizeDAL.Edit(prize);

            return RedirectToAction("Index");
        }
    }
}

17-asp-net-basics/AspNetBasics/AspNetBasics/Controllers/UserController.cs
using AspNetBasics.Models;
using BLL;
using DALDB;
using Entities;
using Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetBasics.Controllers
{
    public class UserController : Controller
    {

        private readonly UserDAL _userDAL;
        private readonly UserBL _userBL;

        private readonly PrizeDAL _prizeDAL;
        private readonly PrizeBL _prizeBL;
        public UserController()
        {
            var connectionStringBuilder = new SqlConnectionStringBuilder();
            connectionStringBuilder.DataSource = "DESKTOP-34RCMFS\\SQLEXPRESS";
            connectionStringBuilder.InitialCatalog = "usersAndPrizes";
            connectionStringBuilder.IntegratedSecurity = true;

            var connection = connectionStringBuilder.ToString();

            _userDAL = new UserDAL(connection);
            _userBL = new UserBL(_userDAL);

            _prizeDAL = new PrizeDAL(connection);
            _prizeBL = new PrizeBL(_prizeDAL);
        }

        public IActionResult Index()
        {
            var users = _userBL.GetAll();
            return View(users);
        }

        public IActionResult Add()
        {
            var model = new AddViewModel();
            model.prizes = _prizeBL.GetAll();
            model.prizesIsChecked = new bool[_prizeBL.GetAll().Count];
            return View(model);
        }

        [HttpPost]
        public IActionResult Add(AddViewModel addViewModel)
        {
            List<Prize> checkedPrizeList = new List<Prize>();
            for(int i = 0; i < _prizeBL.GetAll().Count; i++)
            {
                if(addViewModel.prizesIsChecked[i] == true)
                {
                    checkedPrizeList.Add(_prizeBL.GetAll()[i]);
                }
            }
            User user = new User(addViewModel.User.ID, addViewModel.User.FirstName, addViewModel.User.LastName, addViewModel.User.DateOfBirth.ToString(), checkedPrizeList);
            _userDAL.Add(user);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _userDAL.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var model = new AddViewModel();
            model.User = _userBL.Get(id);
            model.prizes = _prizeBL.GetAll();
            model.prizesIsChecked = new bool[_prizeBL.GetAll().Count];
            for(int i = 0; i < _userBL.Get(id).ListOfPrize.Count; i++)
            {
                for (int j = i; j < _prizeBL.GetAll().Count; j++)
                {
                    if(_userBL.Get(id).ListOfPrize[i].ID == _prizeBL.GetAll()[j].ID)
                    {
                        model.prizesIsChecked[j] = true;
                    }
                }
            }
            
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(AddViewModel addViewModel)
        {
            List<Prize> checkedPrizeList = new List<Prize>();
            for (int i = 0; i < addViewModel.prizesIsChecked.Length; i++)
            {
                if (addViewModel.prizesIsChecked[i])
                {
                    checkedPrizeList.Add(_prizeBL.GetAll()[i]);
                }
                    
            }
            User user = new User(addViewModel.User.ID, addViewModel.User.FirstName, addViewModel.User.LastName, addViewModel.User.DateOfBirth.ToString(), checkedPrizeList);
            _userBL.Edit(user);

            return RedirectToAction("Index");
        }

    }
}

17-asp-net-basics/AspNetBasics/AspNetBasics/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

17-asp-net-basics/AspNetBasics/AspNetBasics/Views/Prize/Add.cshtml
@using Entities
@model Prize
@{
    ViewData["Title"] = "Edit";
}

<div class="prizeForm">
    <form class="form" asp-action="Add">
        <p class="title">Данные награды</p>

        <p class="formText1">Название:</p>
        <input asp-for="Title" type="text" class="name">
        <p class="errorName"></p>

        <p class="formText2">Описание:</p>
        <input asp-for="Description" type="text" class="description">
        <p class="errorDescription"></p>

        <button type="submit" class="acceptBtn">Готово</button>
    </form>
</div>
<script src="~/js/scriptPrize.js" asp-append-version="true"></script>

17-asp-net-basics/AspNetBasics/AspNetBasics/Views/Prize/Edit.cshtml
@using Entities
@model Prize
@{
    ViewData["Title"] = "Edit";
}

<div class="prizeForm">
    <form class="form" asp-action="Edit">
        <p class="title">Данные награды</p>

        <p class="formText1">Название:</p>
        <input asp-for="Title" type="text" class="name">
        <p class="errorName"></p>

        <p class="formText2">Описание:</p>
        <input asp-for="Description" type="text" class="description">
        <p class="errorDescription"></p>

        <button type="submit" class="acceptBtn">Готово</button>
    </form>
</div>
<script src="~/js/scriptPrize.js" asp-append-version="true"></script>

17-asp-net-basics/AspNetBasics/AspNetBasics/Views/Prize/Index.cshtml
@using Entities;
@model IList<Prize>
@{
    ViewData["Title"] = "Index";
}

@{
    ViewData["Title"] = "Index";
}



    <div class="mainUser">
        <a asp-controller="Prize" asp-action="Add" class="add">Добавить</a>

        <table class="table">
            <tr>
                <th onclick="sortTable(0)">ID</th>
                <th onclick="sortTable(1)">Название</th>
                <th onclick="sortTable(2)">Описание</th>
                <td></td>
                <td></td>
            </tr>

            @foreach (var prize in Model)
            {
                <tr>
                    <td name="id">@prize.ID</td>
                    <td name="title">@prize.Title</td>
                    <td name="description">@prize.Description</td>

                    <td><a asp-controller="Prize" asp-action="Edit" asp-route-id="@prize.ID" class="edit">Редактировать</a></td>

                    <form asp-action="Delete">
                        <input type="hidden" value="@prize.ID" name="id">
                    <td><button class="delete" type="submit">Удалить</button></td>
                    </form>
                </tr>
            }
        </table>
    </div>

<script src="~/js/sort.js" asp-append-version="true"></script>

17-asp-net-basics/AspNetBasics/AspNetBasics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="~/css/style.css" />
    <meta charset="utf-8" />
</head>

    <body>
    

        <header>
            <a href="/User" class="mainHref">Пользователи</a>
            <a href="/Prize" class="mainHref">Награды</a>
            <hr class="footerAndHeaderHr">
        </header>


        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">

            <hr class="footerAndHeaderHr">
            <p class="footerText">Рязань, 2021</p>
        </footer>

    </body>
</html>

17-asp-net-basics/AspNetBasics/AspNetBasics/Views/User/Add.cshtml
@using Entities

@model AddViewModel
@{
    ViewData["Title"] = "Add";
}

<body>
    <div class="userForm">
        <form class="form" asp-action="Add">
            <p class="title">Данные пользователя</p>
            <p class="formText1">Имя:</p>
            <input asp-for="User.FirstName" type="text" class="firstName">
            <p class="errorName"></p>

            <p class="formText2">Фамилия:</p>
            <input asp-for="User.LastName" type="text" class="lastName">
            <p class="errorLastName"></p>

            <p class="formText3">Дата рождения:</p>
            <input asp-for="User.DateOfBirth" type="date" class="dateOfBirth">
            <p class="errorDOB"></p>

            <p class="formText4">Награды:</p>


            <table>
                @for (int i = 0; i < Model.prizes.Count; i++)
                {
                    <tr>
                        <td>
                            <input asp-for="prizesIsChecked[i]" type="checkbox" class="prizes"> @Model.prizes[i].Title
                        </td>
                    </tr>
                }
            </table>


            <button type="submit" class="acceptBtn">Готово</button>
        </form>

    </div>


</body>
<script src="~/js/scriptUser.js" asp-append-version="true"></script>

17-asp-net-basics/AspNetBasics/AspNetBasics/Views/User/Edit.cshtml
@using Entities
@model AddViewModel
@{
    ViewData["Title"] = "Edit";
}

<body>
    <div class="userForm">
        <form class="form" asp-action="Edit">
            <input asp-for="User.ID" type="hidden">

            <p class="title">Данные пользователя</p>
            <p class="formText1">Имя:</p>
            <input asp-for="User.FirstName" type="text" class="firstName">
            <p class="errorName"></p>

            <p class="formText2">Фамилия:</p>
            <input asp-for="User.LastName" type="text" class="lastName">
            <p class="errorLastName"></p>

            <p class="formText3">Дата рождения:</p>
            <input asp-for="User.DateOfBirth" type="date" class="dateOfBirth">
            <p class="errorDOB"></p>

            <p class="formText4">Награды:</p>


            <table>
                @for (int i = 0; i < Model.prizes.Count; i++)
                {
                    <tr>
                        <td>
                            <input asp-for="@Model.prizesIsChecked[i]" type="checkbox" class="prizes"> @Model.prizes[i].Title
                        </td>
                    </tr>
                }
            </table>

            <button type="submit" class="acceptBtn">Готово</button>
        </form>

    </div>


</body>
<script src="~/js/scriptUser.js" asp-append-version="true"></script>

17-asp-net-basics/AspNetBasics/AspNetBasics/Views/User/Index.cshtml
@using Entities;
@model IList<User>
@{
    ViewData["Title"] = "Index";
}


    <div class="mainUser">
        <a asp-controller="User" asp-action="Add" class="add">Добавить</a>
        <table class="table">
            <tr>
                <th onclick="sortTable(0)">ID</th>
                <th onclick="sortTable(1)">Имя</th>
                <th onclick="sortTable(2)">Фамилия</th>
                <th onclick="sortTable(3)">Дата рождения</th>
                <th onclick="sortTable(4)">Возраст</th>
                <th onclick="sortTable(5)">Награды</th>
                <td></td>
                <td></td>
            </tr>

            @foreach (var user in Model)
            {
        <tr>
            <td>@user.ID</td>
            <td>@user.FirstName</td>
            <td>@user.LastName</td>
            <td>@user.DateOfBirth.Date</td>
            <td>@user.Age</td>
            <td>@user.PrizeStr</td>

            <td><a asp-controller="User" asp-action="Edit" asp-route-id="@user.ID" class="edit">Редактировать</a></td>

                <form asp-action="Delete">
                    <input type="hidden" value="@user.ID" name="id">
                    <td><button asp-controller="User" asp-action="Delete" class="delete">Удалить</button></td>
                </form>
            </tr>
            }

        </table>
    </div>
    <script src="~/js/sort.js" asp-append-version="true"></script>